import Image from "./Image";

export default function Footer() {
  const logo = "./images/hq.png";
  return (
    <footer className="bg-gray-200 p-4 flex flex-col md:flex-row justify-between items-center text-center gap-4">
      <Image
        image={logo}
        imageStyles={"w-14 rounded-full md:ml-20"}
        altTxt={
          "Logo, Laptop with HQ on the screen with purple background, Image generated by Chatgpt"
        }
      />
      <p className="text-md w-full">© 2025 HabitQuest. All rights Reserved</p>

      <section className="ml-auto hidden md:flex gap-4 text-md mr-20">
        <a href="">Privacy</a>
        <a href="">Terms</a>
      </section>
    </footer>
  );
}
