import Image from "./Image";

export default function Footer() {
  const logo = "./images/hq.png";
  return (
    <footer className="bg-gray-200 p-6 flex justify-between items-center">
      <Image
        image={logo}
        imageStyles={"w-14 rounded-full ml-20"}
        altTxt={
          "Logo, Laptop with HQ on the screen with purple background, Image generated by Chatgpt"
        }
      />
      <p className="flex-1 text-center text-md">
        © 2025 HabitQuest. All rights Reserved
      </p>

      <section className="ml-auto hidden md:flex gap-4 text-md mr-20">
        <a href="">Privacy</a>
        <a href="">Terms</a>
      </section>
    </footer>
  );
}
