import Image from "./Image";

export default function HabitQuestStory() {
  return (
    <section className="max-w-4xl bg-gray-200 rounded-xl p-4">
      <div className="flex gap-4">
        <Image
          image="/images/hq.png"
          imageStyles="w-14 rounded-full"
          alt="Logo, Laptop with HQ on the screen with purple background, Image generated by Chatgpt"
        />
        <div className="flex flex-col">
          <h1>HabitQuest Story</h1>
          <p>Shared by Davonne-007-TX</p>
        </div>
      </div>
    </section>
  );
}
