import Image from "./Image";
import Trails from "./Trails";
import UserIcons from "./UserIcons";

export default function HabitQuestStory() {
  const user = "Shared by @Habitin";

  return (
    <section className="max-w-xl md:max-w-2xl items-center bg-gray-200 rounded-xl p-8 mt-8">
      <div className="flex flex-col gap-4">
        <Image
          image="/images/hq.png"
          imageStyles="w-14 rounded-full"
          alt="Logo, Laptop with HQ on the screen with purple background, Image generated by Chatgpt"
        />
        <div className="flex flex-col ml-2">
          <h1 className="text-xl font-semibold">HabitQuest Story</h1>
          <p>{user}</p>
        </div>
        <Trails />
        <UserIcons />
      </div>
    </section>
  );
}
